hibernate:
  driver-class-name:              org.h2.Driver
  url:                            jdbc:h2:mem:personnes-schema;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;
  username: sa
  password: sa
  dialect: org.hibernate.dialect.H2Dialect
  hbm2ddl:
    auto: create-drop
  show:
    sql: true


spring:
  h2:
    console:
      enabled: true
      path: /h2